config/routes.rb
Rails.application.routes.draw do
  resources :stacks
  resources :tools
  resources :layers
  resources :tags do
    member do
      get 'most_popular_stack'
      get 'most_popular_tools'
    end
  end
  root 'dashboards#home'

end

app/models/tool.rb
class Tool < ActiveRecord::Base
  belongs_to :layer
  has_and_belongs_to_many :stacks

  validates :api_id, :name, :slug, :popularity, :layer_id, presence: true
  validates :api_id, uniqueness: true

  # Syncs up tools from the StackShare API
  def self.sync_from_stackshare_api
    stack_share_service = StackShareService.new

    # First, getting everything from the DB
    all_tools_from_db = Tool.all

    # Then, making as many lookup calls as there are tools, in order to accumulate all the tools with a layer
    all_tools_from_api = []
    Layer.pluck(:api_id).each do |layer_id|
      # Calling the API for just this page
      res = stack_share_service.call_api '/tools/lookup', layer_id: layer_id
      raise "Error when calling StackShare's API to fetch tools: #{res}" unless res.is_a?(Net::HTTPSuccess)
      all_tools_from_api += JSON.parse(res.body)
    end

    # Then, we want to modify the Hash from the API a bit, so that fields match exactly (like: ["layer"]["id"] becomes "layer_id")
    all_tools_from_api.map! do |tool|
      {
        "id" => tool["id"],
        "name" => tool["name"],
        "slug" => tool["slug"],
        "popularity" => tool["popularity"],
        "layer" => stack_share_service.object_from_api_id(Layer, tool["layer"]["id"]),
        "full_object" => tool
      }
    end

    # Finally, syncing it all
    stack_share_service.sync_all(Tool, all_tools_from_db, all_tools_from_api, [:name, :slug, :popularity, :layer, :full_object])
  end
end

app/controllers/tools_controller.rb
class ToolsController < ApplicationController
  before_action :set_tool, only: [:show, :edit, :update, :destroy]
  http_basic_authenticate_with name: "admin", password: Rails.configuration.x.admin_password unless Rails.env.test?

  # GET /tools
  # GET /tools.json
  def index
    @tools = Tool.includes(:layer)
  end

  # GET /tools/1
  # GET /tools/1.json
  def show
    @layer = @tool.layer
  end

  # GET /tools/new
  def new
    @tool = Tool.new
  end

  # GET /tools/1/edit
  def edit
  end

  # POST /tools
  # POST /tools.json
  def create
    @tool = Tool.new(tool_params)

    respond_to do |format|
      if @tool.save
        format.html { redirect_to @tool, notice: 'Tool was successfully created.' }
        format.json { render :show, status: :created, location: @tool }
      else
        format.html { render :new }
        format.json { render json: @tool.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tools/1
  # PATCH/PUT /tools/1.json
  def update
    respond_to do |format|
      if @tool.update(tool_params)
        format.html { redirect_to @tool, notice: 'Tool was successfully updated.' }
        format.json { render :show, status: :ok, location: @tool }
      else
        format.html { render :edit }
        format.json { render json: @tool.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tools/1
  # DELETE /tools/1.json
  def destroy
    @tool.destroy
    respond_to do |format|
      format.html { redirect_to tools_url, notice: 'Tool was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tool
      @tool = Tool.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tool_params
      params.require(:tool).permit(:layer_id, :api_id, :name, :slug, :popularity)
    end
end

app/helpers/tools_helper.rb
module ToolsHelper
end

app/views/tools/_form.html.erb
<%= form_for(@tool) do |f| %>
  <% if @tool.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tool.errors.count, "error") %> prohibited this tool from being saved:</h2>

      <ul>
      <% @tool.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :layer_id %><br>
    <%= f.text_field :layer_id, class: 'form-control' %>
  </div>
  <div class="field">
    <%= f.label :api_id %><br>
    <%= f.number_field :api_id, class: 'form-control' %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name, class: 'form-control' %>
  </div>
  <div class="field">
    <%= f.label :slug %><br>
    <%= f.text_field :slug, class: 'form-control' %>
  </div>
  <div class="field">
    <%= f.label :popularity %><br>
    <%= f.number_field :popularity, class: 'form-control' %>
  </div>
  <div class="actions">
    <%= f.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/tools/_tool.html.erb
<div class="tool">
  <div class="clean well clearfix">
    <p class="logo"><%= image_tag(tool.full_object['image_url'] || 'http://placehold.it/50x50?text=-') %></p>
    <h3><%= tool.name %></h3>
    <p><%= tool.full_object['tag_line'] %></p>
    <ul>
      <% if tool.full_object['canonical_url'].present? %>
        <li><%= link_to 'See on StackShare', tool.full_object['canonical_url'], target: '_blank' %></li>
      <% end %>
      <% if tool.full_object['website_url'].present? %>
        <li><%= link_to 'Website', tool.full_object['website_url'], target: '_blank' %></li>
      <% end %>
      <% if tool.full_object['opensource_url'].present? %>
        <li><%= link_to 'Open source', tool.full_object['opensource_url'], target: '_blank' %></li>
      <% end %>
      <% if tool.full_object['twitter_username'].present? %>
        <li><%= link_to 'Twitter', "https://twitter.com/#{tool.full_object['twitter_username']}", target: '_blank' %></li>
      <% end %>
      <% if tool.full_object['documentation'].present? %>
        <li><%= link_to 'Documentation', tool.full_object['documentation_url'], target: '_blank' %></li>
      <% end %>
    </ul>
  </div>
</div>

app/views/tools/edit.html.erb
<h1>Editing Tool</h1>

<%= render 'form' %>

<%= link_to 'Show', @tool %> |
<%= link_to 'Back', tools_path %>

app/views/tools/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Tools</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Layer</th>
      <th>Api</th>
      <th>Name</th>
      <th>Slug</th>
      <th>Popularity</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tools.each do |tool| %>
      <tr>
        <td><%= tool.layer.slug %></td>
        <td><%= tool.api_id %></td>
        <td><%= tool.name %></td>
        <td><%= tool.slug %></td>
        <td><%= tool.popularity %></td>
        <td><%= link_to 'Show', tool %></td>
        <td><%= link_to 'Edit', edit_tool_path(tool) %></td>
        <td><%= link_to 'Destroy', tool, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tool', new_tool_path %>

app/views/tools/new.html.erb
<h1>New Tool</h1>

<%= render 'form' %>

<%= link_to 'Back', tools_path %>

app/views/tools/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Layer:</strong>
  <%= @layer.slug %>
</p>

<p>
  <strong>Api:</strong>
  <%= @tool.api_id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @tool.name %>
</p>

<p>
  <strong>Slug:</strong>
  <%= @tool.slug %>
</p>

<p>
  <strong>Popularity:</strong>
  <%= @tool.popularity %>
</p>

<p>
  <strong>Full object</strong>
  <pre>
<%= JSON.pretty_generate(@tool.full_object) if @tool.full_object.present? %>
  </pre>
</p>

<%= link_to 'Edit', edit_tool_path(@tool) %> |
<%= link_to 'Back', tools_path %>