config/routes.rb
Rails.application.routes.draw do
  resources :stacks
  resources :tools
  resources :layers
  resources :tags do
    member do
      get 'most_popular_stack'
      get 'most_popular_tools'
    end
  end
  root 'dashboards#home'

end

app/models/stack.rb
class Stack < ActiveRecord::Base
  has_and_belongs_to_many :tools
  has_and_belongs_to_many :tags

  validates :api_id, :name, :slug, :popularity, presence: true
  validates :api_id, uniqueness: true

  # Syncs up stacks from the StackShare API
  # There is some caching in place (sync won't be done if was attempted within the past hour)
  #
  # @param [FixNum] tag_id the ID of the tag as served by the API
  # @param [Boolean] force_cache if set to true, sync no matter what the cache state is
  def self.sync_from_stackshare_api(tag_id, force_cache = false)
    # Caching: checking that this wasn't recently done
    unless force_cache
      @@updated_at_by_tag_id ||= {}
      return if @@updated_at_by_tag_id[tag_id].present? && (Time.now - @@updated_at_by_tag_id[tag_id]) < 1.hour
      @@updated_at_by_tag_id[tag_id] = Time.now
    end

    stack_share_service = StackShareService.new

    # First, getting everything from the DB
    all_stacks_from_db = Stack.joins(:tags).where("tags.id = ?", stack_share_service.object_from_api_id(Tag, tag_id))

    # Calling the API for just this page
    res = stack_share_service.call_api '/stacks/lookup', tag_id: tag_id
    raise "Error when calling StackShare's API to fetch stacks: #{res}" unless res.is_a?(Net::HTTPSuccess)
    all_stacks_from_api = JSON.parse(res.body)

    # Then, we want to modify the Hash from the API a bit, so that fields match exactly (like the tools and tags fields, and populate the full field)
    all_layer_ids = Layer.order(:id).pluck(:id)
    all_stacks_from_api.map! { |stack|
      tools = stack["tools"].map{ |t| stack_share_service.object_from_api_id(Tool, t["id"]) }.compact
      {
        "id" => stack["id"],
        "name" => stack["name"],
        "slug" => stack["slug"],
        "popularity" => stack["popularity"],
        "tools" => tools,
        "tags" => stack["tags"].map{|t|stack_share_service.object_from_api_id(Tag, t["id"])}.compact,
        "tool_layer_count" => tools.map(&:layer_id).uniq.size,
        "verified" => stack["verified"],
        "full_object" => stack
      }
    }

    # Finally, syncing it all
    stack_share_service.sync_all(Stack, all_stacks_from_db, all_stacks_from_api, [:name, :slug, :popularity, :tools, :tags, :verified, :tool_layer_count, :full_object])
  end
end

app/controllers/stacks_controller.rb
class StacksController < ApplicationController
  before_action :set_stack, only: [:show, :edit, :update, :destroy]
  http_basic_authenticate_with name: "admin", password: Rails.configuration.x.admin_password unless Rails.env.test?

  # GET /stacks
  # GET /stacks.json
  def index
    @stacks = Stack.all
  end

  # GET /stacks/1
  # GET /stacks/1.json
  def show
    @tags = @stack.tags
    @tools = @stack.tools
  end

  # GET /stacks/new
  def new
    @stack = Stack.new
  end

  # GET /stacks/1/edit
  def edit
  end

  # POST /stacks
  # POST /stacks.json
  def create
    @stack = Stack.new(stack_params)

    respond_to do |format|
      if @stack.save
        format.html { redirect_to @stack, notice: 'Stack was successfully created.' }
        format.json { render :show, status: :created, location: @stack }
      else
        format.html { render :new }
        format.json { render json: @stack.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stacks/1
  # PATCH/PUT /stacks/1.json
  def update
    respond_to do |format|
      if @stack.update(stack_params)
        format.html { redirect_to @stack, notice: 'Stack was successfully updated.' }
        format.json { render :show, status: :ok, location: @stack }
      else
        format.html { render :edit }
        format.json { render json: @stack.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stacks/1
  # DELETE /stacks/1.json
  def destroy
    @stack.destroy
    respond_to do |format|
      format.html { redirect_to stacks_url, notice: 'Stack was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_stack
      @stack = Stack.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def stack_params
      params.require(:stack).permit(:api_id, :name, :slug, :popularity)
    end
end

app/helpers/stacks_helper.rb
module StacksHelper
end

app/views/stacks/_form.html.erb
<%= form_for(@stack) do |f| %>
  <% if @stack.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@stack.errors.count, "error") %> prohibited this stack from being saved:</h2>

      <ul>
      <% @stack.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :api_id %><br>
    <%= f.number_field :api_id, class: 'form-control' %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name, class: 'form-control' %>
  </div>
  <div class="field">
    <%= f.label :slug %><br>
    <%= f.text_field :slug, class: 'form-control' %>
  </div>
  <div class="field">
    <%= f.label :popularity %><br>
    <%= f.number_field :popularity, class: 'form-control' %>
  </div>
  <div class="actions">
    <%= f.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/stacks/edit.html.erb
<h1>Editing Stack</h1>

<%= render 'form' %>

<%= link_to 'Show', @stack %> |
<%= link_to 'Back', stacks_path %>

app/views/stacks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Stacks</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Api</th>
      <th>Name</th>
      <th>Slug</th>
      <th>Popularity</th>
      <th>Tool layer count</th>
      <th>Verified</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @stacks.each do |stack| %>
      <tr>
        <td><%= stack.api_id %></td>
        <td><%= stack.name %></td>
        <td><%= stack.slug %></td>
        <td><%= stack.popularity %></td>
        <td><%= stack.tool_layer_count %></td>
        <td><%= stack.verified? %></td>
        <td><%= link_to 'Show', stack %></td>
        <td><%= link_to 'Edit', edit_stack_path(stack) %></td>
        <td><%= link_to 'Destroy', stack, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Stack', new_stack_path %>

app/views/stacks/new.html.erb
<h1>New Stack</h1>

<%= render 'form' %>

<%= link_to 'Back', stacks_path %>

app/views/stacks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Api:</strong>
  <%= @stack.api_id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @stack.name %>
</p>

<p>
  <strong>Slug:</strong>
  <%= @stack.slug %>
</p>

<p>
  <strong>Popularity:</strong>
  <%= @stack.popularity %>
</p>

<p>
  <strong>Tool layer count:</strong>
  <%= @stack.tool_layer_count %>
</p>

<p>
  <strong>Verified:</strong>
  <%= @stack.verified? %>
</p>

<p>
  <strong>Full object</strong>
  <pre>
<%= JSON.pretty_generate(@stack.full_object) if @stack.full_object.present? %>
  </pre>
</p>

<p>
  <strong>Tags:</strong>
  <% if @tags.empty? %>
    - none -
  <% else %>
    <ul>
      <% @tags.each do |tag| %>
        <li>
          <%= link_to tag.name, tag %>
        </li>
      <% end %>
    </ul>
  <% end %>
</p>

<p>
  <strong>Tools:</strong>
  <% if @tools.empty? %>
    - none -
  <% else %>
    <ul>
      <% @tools.each do |tool| %>
        <li>
          <%= link_to tool.name, tool %>
        </li>
      <% end %>
    </ul>
  <% end %>
</p>

<%= link_to 'Edit', edit_stack_path(@stack) %> |
<%= link_to 'Back', stacks_path %>