config/routes.rb
Rails.application.routes.draw do
  resources :stacks
  resources :tools
  resources :layers
  resources :tags do
    member do
      get 'most_popular_stack'
      get 'most_popular_tools'
    end
  end
  root 'dashboards#home'

end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_and_belongs_to_many :stacks

  validates :api_id, :name, presence: true
  validates :api_id, uniqueness: true

  # Syncs up tags from the StackShare API
  def self.sync_from_stackshare_api
    stack_share_service = StackShareService.new
    # First, getting everything from both datasources
    all_tags_from_db = Tag.all
    all_tags_from_api = api_fetch_all_tags_from_page(1, stack_share_service)
    # Then, we want to modify the Hash from the API a bit, so that fields match exactly (like: "humanized_name")
    all_tags_from_api.map! do |tag|
      {
        "id" => tag["id"],
        "name" => tag["name"],
        "humanized_name" => tag["name"].gsub("-", " ").split.map(&:capitalize).join(' ')
      }
    end
    # Then syncing
    stack_share_service.sync_all(Tag, all_tags_from_db, all_tags_from_api, [:name, :humanized_name])
  end

  # Recursive function to return all tags of all pages from a certain page number
  #
  # @param [FixNum] page the page number where to start
  # @return [Array<Hash>] all the existing tags in one array
  def self.api_fetch_all_tags_from_page(page, stack_share_service)
    # Calling the API for just this page
    res = stack_share_service.call_api '/stacks/tags', page: page

    if res.is_a?(Net::HTTPNotFound)  # This happens for the page after the last one -> base case
      []
    elsif res.is_a?(Net::HTTPSuccess)  # This is an existing page -> recursion
      JSON.parse(res.body) + api_fetch_all_tags_from_page(page+1, stack_share_service)
    else
      raise "Error when calling StackShare's API to fetch pages: #{res}"
    end
  end

  # Will build a list of the tools by order of popularity for the current tag, on verified stacks.
  #
  # @param [Boolean] include_not_verified also include stacks that are not verified
  # @return [Array<Tool>] most popular tools in order
  def most_popular_tools(include_not_verified= false)
    # First, we're building a hash { id_tool => accumulated_score }
    accumulated_scores = Hash.new(0)
    Stack.includes(:tools).joins(:tags).where('tags.id = ?', self.id).where(verified: include_not_verified ? [true, false] : true).find_each do |stack|
      stack.tool_ids.each do |tool_id|
        accumulated_scores[tool_id] += 1
      end
    end
    # Winning some time if there's no result
    return [] if accumulated_scores.empty?
    # Then, reverse-sorting this hash, and returning its keys, to get the IDs in order
    tool_ids = accumulated_scores.sort_by{|_,value| value}.reverse.map(&:first)
    # We could query each Tool, and the code would look good, but we should really group these queries into one
    tools_by_id = Tool.where(id: tool_ids).group_by(&:id)
    tool_ids.map{|id| tools_by_id[id].first}
  end

  # For the current tag, finds the most popular stack with the highest possible number of layers.
  #
  # @return [Stack]
  def most_popular_full_stack
    most_popular_stack_closest_to(Layer.count)
  end

  private

  # Recursive function to find the most popular stack of the current tag with a number of tool layers, but if there
  # is no such stack, will look successively in stacks with less layers.
  #
  # @param [FixNum] nb_layers the number of layers to look at currently
  # @return [Stack,nil] either the Stack, ot nil if there's none regardless of number of layers
  def most_popular_stack_closest_to(nb_layers)
    stacks = Stack.joins(:tags).order(popularity: :desc).where('tags.id = ?', self.id).where(tool_layer_count: nb_layers).limit(1)
    if nb_layers == -1
      nil
    elsif stacks.empty?
      most_popular_stack_closest_to(nb_layers - 1)
    else
      stacks.first
    end
  end

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

  before_action :set_tag, only: [:show, :edit, :update, :destroy, :most_popular_stack, :most_popular_tools]
  http_basic_authenticate_with name: "admin", password: Rails.configuration.x.admin_password, except: [:index,:most_popular_stack,:most_popular_tools] unless Rails.env.test?

  # GET /tags
  # GET /tags.json
  def index
    @tags = Tag.order(:name)
  end

  # GET /tags/1
  # GET /tags/1.json
  def show
  end

  # GET /tags/new
  def new
    @tag = Tag.new
  end

  # GET /tags/1/edit
  def edit
  end

  # POST /tags
  # POST /tags.json
  def create
    @tag = Tag.new(tag_params)

    respond_to do |format|
      if @tag.save
        format.html { redirect_to @tag, notice: 'Tag was successfully created.' }
        format.json { render :show, status: :created, location: @tag }
      else
        format.html { render :new }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tags/1
  # PATCH/PUT /tags/1.json
  def update
    respond_to do |format|
      if @tag.update(tag_params)
        format.html { redirect_to @tag, notice: 'Tag was successfully updated.' }
        format.json { render :show, status: :ok, location: @tag }
      else
        format.html { render :edit }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tags/1
  # DELETE /tags/1.json
  def destroy
    @tag.destroy
    respond_to do |format|
      format.html { redirect_to tags_url, notice: 'Tag was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def most_popular_stack
    # First, let's sync up the stacks for this tag
    begin
      Stack.sync_from_stackshare_api @tag.api_id
    rescue
      render inline: "There is currently a problem with StackShare's API; contact them, and come back here later!", layout: 'application'
    end

    # Getting the most popular stack
    @most_popular_stack = @tag.most_popular_full_stack
    # If there is one, fetching / parsing some more needed data
    if @most_popular_stack.present?
      @company = JSON.parse @most_popular_stack.full_object['company'].gsub('=>',':').gsub(':nil',':null')
      @tags = JSON.parse @most_popular_stack.full_object['tags'].gsub('=>',':').gsub(':nil',':null')
      @tools_by_layer_id = @most_popular_stack.tools.group_by(&:layer_id)
      @all_layers = Layer.order :api_id
    end
    # Storing it so that we can display a warning to the user that a stack is not full, when it's not.
    @total_nb_layers = Layer.count
  end

  def most_popular_tools
    # First, let's sync up the stacks for this tag
    begin
      Stack.sync_from_stackshare_api @tag.api_id
    rescue
      render inline: "There is currently a problem with StackShare's API; contact them, and come back here later!", layout: 'application'
    end

    # Most popular tools
    @most_popular_tools = @tag.most_popular_tools
    @included_not_verified = false
    if @most_popular_tools.empty?
      @most_popular_tools = @tag.most_popular_tools(true)
      @included_not_verified = true
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tag
      @tag = Tag.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tag_params
      params.require(:tag).permit(:name, :api_id)
    end
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/tags/_form.html.erb
<%= form_for(@tag) do |f| %>
  <% if @tag.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tag.errors.count, "error") %> prohibited this tag from being saved:</h2>

      <ul>
      <% @tag.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name, class: 'form-control' %>
  </div>
  <div class="field">
    <%= f.label :api_id %><br>
    <%= f.number_field :api_id, class: 'form-control' %>
  </div>
  <div class="actions">
    <%= f.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/tags/advice.html.erb
<article id="advice">
  <h1>
    Most popular full stack for "<%= @tag.humanized_name %>"<%= @most_popular_stack.present? ? ": #{@most_popular_stack.name}" : '' %>
  </h1>

  <% if @most_popular_stack.nil? %>
    <p class="gap">There is no known stack with the tag "<%= @tag.humanized_name %>".</p>
  <% else %>

    <% if @total_nb_layers != @most_popular_stack.tool_layer_count %>
      <div class="alert alert-info sm-gap">
        There is no stack with the tag "<%= @tag.humanized_name %>" that has all <%= @total_nb_layers %> layers of tools,
        but here's the best next thing: the most popular stack with <%= @most_popular_stack.tool_layer_count %> layers of tools.
      </div>
    <% end %>

    <div class="gap">
      <% @all_layers.each_with_index do |layer, index| %>
        <% if index != 0 %><hr><% end %>
        <section class="layer" class="gap">
          <h2><%= layer.name %></h2>
          <% if @tools_by_layer_id[layer.id].nil? || @tools_by_layer_id[layer.id].empty? %>
            <p><em>- unknown -</em></p>
          <% else %>
            <% @tools_by_layer_id[layer.id].each do |tool| %>
              <div class="clean well clearfix">
                <p class="logo"><%= image_tag(tool.full_object['image_url'] || 'http://placehold.it/50x50?text=-') %></p>
                <h3><%= tool.name %></h3>
                <p><%= tool.full_object['tag_line'] %></p>
                <ul>
                  <% if tool.full_object['canonical_url'].present? %>
                    <li><%= link_to 'See on StackShare', tool.full_object['canonical_url'], target: '_blank' %></li>
                  <% end %>
                  <% if tool.full_object['website_url'].present? %>
                    <li><%= link_to 'Website', tool.full_object['website_url'], target: '_blank' %></li>
                  <% end %>
                  <% if tool.full_object['opensource_url'].present? %>
                    <li><%= link_to 'Open source', tool.full_object['opensource_url'], target: '_blank' %></li>
                  <% end %>
                  <% if tool.full_object['twitter_username'].present? %>
                    <li><%= link_to 'Twitter', "https://twitter.com/#{tool.full_object['twitter_username']}", target: '_blank' %></li>
                  <% end %>
                  <% if tool.full_object['documentation'].present? %>
                    <li><%= link_to 'Documentation', tool.full_object['documentation_url'], target: '_blank' %></li>
                  <% end %>
                </ul>
              </div>
            <% end %>
          <% end %>
        </section>
      <% end %>
    </div>

    <section id="about" class="gap well clearfix">
      <p class="logo"><%= image_tag(@company['image_url'] || 'http://placehold.it/100x100?text=-') %></p>
      <h2>About <%= @most_popular_stack.name %></h2>
      <p><%= @company['description'] %> - <%= @company['location'] %></p>
      <ul>
        <% if @company['canonical_url'].present? %>
          <li><%= link_to 'See on StackShare', @company['canonical_url'], target: '_blank' %></li>
        <% end %>
        <% if @company['website_url'].present? %>
          <li><%= link_to 'Website', @company['website_url'], target: '_blank' %></li>
        <% end %>
        <% if @company['angellist_url'].present? %>
          <li><%= link_to 'AngelList', @company['angellist_url'], target: '_blank' %></li>
        <% end %>
        <% if @company['twitter_username'].present? %>
          <li><%= link_to 'Twitter', "https://twitter.com/#{@company['twitter_username']}", target: '_blank' %></li>
        <% end %>
      </ul>
      <p>
        Tags: <%= @tags.map{|t| t['name']}.join(', ') %>
      </p>
    </section>
  <% end %>
</article>

app/views/tags/edit.html.erb
<h1>Editing Tag</h1>

<%= render 'form' %>

<%= link_to 'Show', @tag %> |
<%= link_to 'Back', tags_path %>

app/views/tags/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Tags</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Humanized name</th>
      <th>Api</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tags.each do |tag| %>
      <tr>
        <td><%= tag.name %></td>
        <td><%= tag.humanized_name %></td>
        <td><%= tag.api_id %></td>
        <td><%= link_to 'Show', tag %></td>
        <td><%= link_to 'Edit', edit_tag_path(tag) %></td>
        <td><%= link_to 'Destroy', tag, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tag', new_tag_path %>

app/views/tags/most_popular_stack.html.erb
<article id="advice">
  <h1>
    Most popular full stack for "<%= @tag.humanized_name %>"<%= @most_popular_stack.present? ? ": #{@most_popular_stack.name}" : '' %>
  </h1>

  <% if @most_popular_stack.nil? %>
    <p class="gap">There is no known stack with the tag "<%= @tag.humanized_name %>".</p>
  <% else %>

    <% if @total_nb_layers != @most_popular_stack.tool_layer_count %>
      <div class="alert alert-info sm-gap">
        There is no stack with the tag "<%= @tag.humanized_name %>" that has all <%= @total_nb_layers %> layers of tools,
        but here's the best next thing: the most popular stack with <%= @most_popular_stack.tool_layer_count %> layers of tools.
      </div>
    <% end %>

    <div class="gap">
      <% @all_layers.each_with_index do |layer, index| %>
        <% if index != 0 %><hr><% end %>
        <section class="layer" class="gap">
          <h2><%= layer.name %></h2>
          <% if @tools_by_layer_id[layer.id].nil? || @tools_by_layer_id[layer.id].empty? %>
            <p><em>- unknown -</em></p>
          <% else %>
            <% @tools_by_layer_id[layer.id].each do |tool| %>
              <%= render tool %>
            <% end %>
          <% end %>
        </section>
      <% end %>
    </div>

    <section id="about" class="gap well clearfix">
      <p class="logo"><%= image_tag(@company['image_url'] || 'http://placehold.it/100x100?text=-') %></p>
      <h2>About <%= @most_popular_stack.name %></h2>
      <p><%= @company['description'] %> - <%= @company['location'] %></p>
      <ul>
        <% if @company['canonical_url'].present? %>
          <li><%= link_to 'See on StackShare', @company['canonical_url'], target: '_blank' %></li>
        <% end %>
        <% if @company['website_url'].present? %>
          <li><%= link_to 'Website', @company['website_url'], target: '_blank' %></li>
        <% end %>
        <% if @company['angellist_url'].present? %>
          <li><%= link_to 'AngelList', @company['angellist_url'], target: '_blank' %></li>
        <% end %>
        <% if @company['twitter_username'].present? %>
          <li><%= link_to 'Twitter', "https://twitter.com/#{@company['twitter_username']}", target: '_blank' %></li>
        <% end %>
      </ul>
      <p>
        Tags: <%= @tags.map{|t| t['name']}.join(', ') %>
      </p>
    </section>
  <% end %>
</article>

app/views/tags/most_popular_tools.html.erb
<h2>Most popular tools in order for the tag "<%= @tag.humanized_name %>"</h2>

<div class="gap">
  <% if @most_popular_tools.empty? %>
   <p class="text-center"><em>No tool is known as used for this tag.</em></p>
  <% else %>

    <% if @included_not_verified %>
      <div class="alert alert-info sm-gap">
        No verified stack with the tag "<%= @tag.humanized_name %>" contains known tools, so we've included non-verified stacks.
      </div>
    <% end %>

    <% @most_popular_tools.each do |tool| %>
      <%= render tool %>
    <% end %>

  <% end %>
</div>

app/views/tags/new.html.erb
<h1>New Tag</h1>

<%= render 'form' %>

<%= link_to 'Back', tags_path %>

app/views/tags/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @tag.name %>
</p>

<p>
  <strong>Humanized name:</strong>
  <%= @tag.humanized_name %>
</p>

<p>
  <strong>Api:</strong>
  <%= @tag.api_id %>
</p>

<%= link_to 'Edit', edit_tag_path(@tag) %> |
<%= link_to 'Back', tags_path %>