config/routes.rb
Rails.application.routes.draw do
  resources :stacks
  resources :tools
  resources :layers
  resources :tags do
    member do
      get 'most_popular_stack'
      get 'most_popular_tools'
    end
  end
  root 'dashboards#home'

end

app/models/layer.rb
class Layer < ActiveRecord::Base
  has_many :tools, dependent: :destroy

  validates :api_id, :name, :slug, presence: true
  validates :api_id, uniqueness: true

  # Syncs up layers from the StackShare API
  def self.sync_from_stackshare_api
    stack_share_service = StackShareService.new

    # First, getting everything from the DB
    all_layers_from_db = Layer.all

    # Calling the API
    res = stack_share_service.call_api '/tools/layers'
    raise "Error when calling StackShare's API to fetch layers: #{res}" unless res.is_a?(Net::HTTPSuccess)
    all_layers_from_api = JSON.parse(res.body)

    # Syncing
    stack_share_service.sync_all(Layer, all_layers_from_db, all_layers_from_api, [:name, :slug])
  end
end

app/controllers/layers_controller.rb
class LayersController < ApplicationController
  before_action :set_layer, only: [:show, :edit, :update, :destroy]
  http_basic_authenticate_with name: "admin", password: Rails.configuration.x.admin_password unless Rails.env.test?

  # GET /layers
  # GET /layers.json
  def index
    @layers = Layer.all
  end

  # GET /layers/1
  # GET /layers/1.json
  def show
  end

  # GET /layers/new
  def new
    @layer = Layer.new
  end

  # GET /layers/1/edit
  def edit
  end

  # POST /layers
  # POST /layers.json
  def create
    @layer = Layer.new(layer_params)

    respond_to do |format|
      if @layer.save
        format.html { redirect_to @layer, notice: 'Layer was successfully created.' }
        format.json { render :show, status: :created, location: @layer }
      else
        format.html { render :new }
        format.json { render json: @layer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /layers/1
  # PATCH/PUT /layers/1.json
  def update
    respond_to do |format|
      if @layer.update(layer_params)
        format.html { redirect_to @layer, notice: 'Layer was successfully updated.' }
        format.json { render :show, status: :ok, location: @layer }
      else
        format.html { render :edit }
        format.json { render json: @layer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /layers/1
  # DELETE /layers/1.json
  def destroy
    @layer.destroy
    respond_to do |format|
      format.html { redirect_to layers_url, notice: 'Layer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_layer
      @layer = Layer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def layer_params
      params.require(:layer).permit(:api_id, :name, :slug)
    end
end

app/helpers/layers_helper.rb
module LayersHelper
end

app/views/layers/_form.html.erb
<%= form_for(@layer) do |f| %>
  <% if @layer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@layer.errors.count, "error") %> prohibited this layer from being saved:</h2>

      <ul>
      <% @layer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :api_id %><br>
    <%= f.number_field :api_id, class: 'form-control' %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name, class: 'form-control' %>
  </div>
  <div class="field">
    <%= f.label :slug %><br>
    <%= f.text_field :slug, class: 'form-control' %>
  </div>
  <div class="actions">
    <%= f.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/layers/edit.html.erb
<h1>Editing Layer</h1>

<%= render 'form' %>

<%= link_to 'Show', @layer %> |
<%= link_to 'Back', layers_path %>

app/views/layers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Layers</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Api</th>
      <th>Name</th>
      <th>Slug</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @layers.each do |layer| %>
      <tr>
        <td><%= layer.api_id %></td>
        <td><%= layer.name %></td>
        <td><%= layer.slug %></td>
        <td><%= link_to 'Show', layer %></td>
        <td><%= link_to 'Edit', edit_layer_path(layer) %></td>
        <td><%= link_to 'Destroy', layer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Layer', new_layer_path %>

app/views/layers/new.html.erb
<h1>New Layer</h1>

<%= render 'form' %>

<%= link_to 'Back', layers_path %>

app/views/layers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Api:</strong>
  <%= @layer.api_id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @layer.name %>
</p>

<p>
  <strong>Slug:</strong>
  <%= @layer.slug %>
</p>

<%= link_to 'Edit', edit_layer_path(@layer) %> |
<%= link_to 'Back', layers_path %>